// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/prob.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Prob message.
type Prob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total       float64   `protobuf:"fixed64,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Sum         float64   `protobuf:"fixed64,2,opt,name=Sum,proto3" json:"Sum,omitempty"`
	Values      []float64 `protobuf:"fixed64,3,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	CountInt32  []int32   `protobuf:"varint,4,rep,packed,name=CountInt32,proto3" json:"CountInt32,omitempty"`
	CountInt64  []int64   `protobuf:"varint,5,rep,packed,name=CountInt64,proto3" json:"CountInt64,omitempty"`
	CountUint32 []uint32  `protobuf:"varint,6,rep,packed,name=CountUint32,proto3" json:"CountUint32,omitempty"`
	CountUint64 []uint64  `protobuf:"varint,7,rep,packed,name=CountUint64,proto3" json:"CountUint64,omitempty"`
	CountFloat  []float32 `protobuf:"fixed32,8,rep,packed,name=CountFloat,proto3" json:"CountFloat,omitempty"`
	CountDouble []float64 `protobuf:"fixed64,9,rep,packed,name=CountDouble,proto3" json:"CountDouble,omitempty"`
	CountString []string  `protobuf:"bytes,10,rep,name=CountString,proto3" json:"CountString,omitempty"`
}

func (x *Prob) Reset() {
	*x = Prob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_prob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prob) ProtoMessage() {}

func (x *Prob) ProtoReflect() protoreflect.Message {
	mi := &file_pb_prob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prob.ProtoReflect.Descriptor instead.
func (*Prob) Descriptor() ([]byte, []int) {
	return file_pb_prob_proto_rawDescGZIP(), []int{0}
}

func (x *Prob) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Prob) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Prob) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Prob) GetCountInt32() []int32 {
	if x != nil {
		return x.CountInt32
	}
	return nil
}

func (x *Prob) GetCountInt64() []int64 {
	if x != nil {
		return x.CountInt64
	}
	return nil
}

func (x *Prob) GetCountUint32() []uint32 {
	if x != nil {
		return x.CountUint32
	}
	return nil
}

func (x *Prob) GetCountUint64() []uint64 {
	if x != nil {
		return x.CountUint64
	}
	return nil
}

func (x *Prob) GetCountFloat() []float32 {
	if x != nil {
		return x.CountFloat
	}
	return nil
}

func (x *Prob) GetCountDouble() []float64 {
	if x != nil {
		return x.CountDouble
	}
	return nil
}

func (x *Prob) GetCountString() []string {
	if x != nil {
		return x.CountString
	}
	return nil
}

var File_pb_prob_proto protoreflect.FileDescriptor

var file_pb_prob_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xae, 0x02, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x53, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x20, 0x0a, 0x0b,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x08,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x0a, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_prob_proto_rawDescOnce sync.Once
	file_pb_prob_proto_rawDescData = file_pb_prob_proto_rawDesc
)

func file_pb_prob_proto_rawDescGZIP() []byte {
	file_pb_prob_proto_rawDescOnce.Do(func() {
		file_pb_prob_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_prob_proto_rawDescData)
	})
	return file_pb_prob_proto_rawDescData
}

var file_pb_prob_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_prob_proto_goTypes = []interface{}{
	(*Prob)(nil), // 0: pb.Prob
}
var file_pb_prob_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_prob_proto_init() }
func file_pb_prob_proto_init() {
	if File_pb_prob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_prob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_prob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_prob_proto_goTypes,
		DependencyIndexes: file_pb_prob_proto_depIdxs,
		MessageInfos:      file_pb_prob_proto_msgTypes,
	}.Build()
	File_pb_prob_proto = out.File
	file_pb_prob_proto_rawDesc = nil
	file_pb_prob_proto_goTypes = nil
	file_pb_prob_proto_depIdxs = nil
}
